-- MySQL Script generated by MySQL Workbench
-- Mon Aug 18 10:51:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema admindb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `admindb` ;

-- -----------------------------------------------------
-- Schema admindb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admindb` DEFAULT CHARACTER SET utf8 ;
USE `admindb` ;

-- -----------------------------------------------------
-- Table `admindb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admindb`.`role` ;

CREATE TABLE IF NOT EXISTS `admindb`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `nom_role` VARCHAR(255) NOT NULL,
  `acronyme_role` VARCHAR(255) NOT NULL,
  `del` TINYINT(1) ZEROFILL NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `nom_role_UNIQUE` (`nom_role` ASC) VISIBLE,
  UNIQUE INDEX `acronyme_role_UNIQUE` (`acronyme_role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admindb`.`identity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admindb`.`identity` ;

CREATE TABLE IF NOT EXISTS `admindb`.`identity` (
  `identity_id` INT NOT NULL AUTO_INCREMENT,
  `nom_admin` VARCHAR(255) NOT NULL,
  `prenom_admin` VARCHAR(255) NOT NULL,
  `email_admin` VARCHAR(255) NULL,
  `telephone_admin` INT NOT NULL,
  `del` TINYINT(1) ZEROFILL NULL,
  PRIMARY KEY (`identity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admindb`.`user_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admindb`.`user_admin` ;

CREATE TABLE IF NOT EXISTS `admindb`.`user_admin` (
  `iduser_admin` INT NOT NULL AUTO_INCREMENT,
  `username_admin` VARCHAR(255) NOT NULL,
  `password_admin` VARCHAR(255) NOT NULL,
  `del` TINYINT(1) ZEROFILL NULL,
  `identity_ididentity` INT NOT NULL,
  PRIMARY KEY (`iduser_admin`, `identity_ididentity`),
  UNIQUE INDEX `username_admin_UNIQUE` (`username_admin` ASC) VISIBLE,
  INDEX `fk_user_admin_identity1_idx` (`identity_ididentity` ASC) VISIBLE,
  CONSTRAINT `fk_user_admin_identity1`
    FOREIGN KEY (`identity_ididentity`)
    REFERENCES `admindb`.`identity` (`identity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admindb`.`boutique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admindb`.`boutique` ;

CREATE TABLE IF NOT EXISTS `admindb`.`boutique` (
  `boutique_id` INT NOT NULL AUTO_INCREMENT,
  `nom_boutique` VARCHAR(255) NOT NULL,
  `adresse_boutique` VARCHAR(255) NOT NULL,
  `telephone_boutique` INT NOT NULL,
  `del` TINYINT(1) ZEROFILL NULL,
  PRIMARY KEY (`boutique_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admindb`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admindb`.`articles` ;

CREATE TABLE IF NOT EXISTS `admindb`.`articles` (
  `articles_id` INT NOT NULL AUTO_INCREMENT,
  `nom_articles` VARCHAR(255) NOT NULL,
  `description_articles` VARCHAR(255) NULL,
  `stock_articles` INT NOT NULL,
  `del` TINYINT(1) ZEROFILL NULL,
  PRIMARY KEY (`articles_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admindb`.`user_admin_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admindb`.`user_admin_role` ;

CREATE TABLE IF NOT EXISTS `admindb`.`user_admin_role` (
  `user_admin_iduser_admin` INT NOT NULL,
  `role_idrole` INT NOT NULL,
  PRIMARY KEY (`user_admin_iduser_admin`, `role_idrole`),
  INDEX `fk_user_admin_has_role_role1_idx` (`role_idrole` ASC) VISIBLE,
  INDEX `fk_user_admin_has_role_user_admin1_idx` (`user_admin_iduser_admin` ASC) VISIBLE,
  CONSTRAINT `fk_user_admin_has_role_user_admin1`
    FOREIGN KEY (`user_admin_iduser_admin`)
    REFERENCES `admindb`.`user_admin` (`iduser_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_admin_has_role_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `admindb`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admindb`.`useradmin_has_boutique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admindb`.`useradmin_has_boutique` ;

CREATE TABLE IF NOT EXISTS `admindb`.`useradmin_has_boutique` (
  `boutique_idboutique` INT NOT NULL,
  `user_admin_iduser_admin` INT NOT NULL,
  `user_admin_identity_ididentity` INT NOT NULL,
  PRIMARY KEY (`boutique_idboutique`, `user_admin_iduser_admin`, `user_admin_identity_ididentity`),
  INDEX `fk_boutique_has_user_admin_user_admin1_idx` (`user_admin_iduser_admin` ASC, `user_admin_identity_ididentity` ASC) VISIBLE,
  INDEX `fk_boutique_has_user_admin_boutique1_idx` (`boutique_idboutique` ASC) VISIBLE,
  CONSTRAINT `fk_boutique_has_user_admin_boutique1`
    FOREIGN KEY (`boutique_idboutique`)
    REFERENCES `admindb`.`boutique` (`boutique_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boutique_has_user_admin_user_admin1`
    FOREIGN KEY (`user_admin_iduser_admin` , `user_admin_identity_ididentity`)
    REFERENCES `admindb`.`user_admin` (`iduser_admin` , `identity_ididentity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admindb`.`articles_has_boutique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admindb`.`articles_has_boutique` ;

CREATE TABLE IF NOT EXISTS `admindb`.`articles_has_boutique` (
  `articles_idarticles` INT NOT NULL,
  `boutique_idboutique` INT NOT NULL,
  PRIMARY KEY (`articles_idarticles`, `boutique_idboutique`),
  INDEX `fk_articles_has_boutique_boutique1_idx` (`boutique_idboutique` ASC) VISIBLE,
  INDEX `fk_articles_has_boutique_articles1_idx` (`articles_idarticles` ASC) VISIBLE,
  CONSTRAINT `fk_articles_has_boutique_articles1`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `admindb`.`articles` (`articles_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_boutique_boutique1`
    FOREIGN KEY (`boutique_idboutique`)
    REFERENCES `admindb`.`boutique` (`boutique_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;